production:
  emails:
     broken_links:
        - ihz2@cornell.edu
        - lrector@nescaum.org
        - cary.fitzhugh@gmail.com
     feedback:
        - ihz2@cornell.edu
        - lrector@nescaum.org
        - cary.fitzhugh@gmail.com

  postgres:
     adapter: postgres
     database: <%= ENV['RDS_DB_NAME'] %>
     username: <%= ENV['RDS_USERNAME'] %>
     password: <%= ENV['RDS_PASSWORD'] %>
     host: <%= ENV['RDS_HOSTNAME'] %>
     port: <%= ENV['RDS_PORT'] %>

  postgres_geoserver:
     adapter: postgres
     database: <%= ENV['GEOSERVER_RDS_DB_NAME'] %>
     username: <%= ENV['GEOSERVER_RDS_USERNAME'] %>
     password: <%= ENV['GEOSERVER_RDS_PASSWORD'] %>
     host: <%= ENV['GEOSERVER_RDS_HOSTNAME'] %>
     port: <%= ENV['GEOSERVER_RDS_PORT'] %>
  cs:
    env: <%= ENV["CLOUDSEARCH_ENV"] %>
    search_endpoint: <%= ENV["CLOUDSEARCH_SEARCH_ENDPOINT"] %>
    doc_endpoint: <%= ENV["CLOUDSEARCH_DOC_ENDPOINT"] %>
    access_key: <%= ENV["CLOUDSEARCH_ACCESS_KEY"] %>
    secret_key: <%= ENV["CLOUDSEARCH_SECRET_KEY"] %>

development:
  emails:
     broken_links:
        - cary.fitzhugh@gmail.com
  postgres:
    adapter: <%= ENV['POSTGRES_DB_ADAPTER'] || 'postgres' %>
    database: <%= ENV['POSTGRES_DB_DATABASE'] || 'nds' %>
    username: <%= ENV['POSTGRES_DB_USERNAME'] || 'nds' %>
    password: <%= ENV['POSTGRES_DB_PASSWORD'] || 'nds' %>
    host: <%= ENV['POSTGRES_DB_HOST'] || 'localhost' %>
    port: <%= ENV['POSTGRES_DB_PORT'] || '5000' %>
  postgres_geoserver:
    adapter: <%= ENV['GEOSERVER_DB_ADAPTER'] || 'postgres' %>
    database: <%= ENV['GEOSERVER_DB_DATABASE'] || 'nds' %>
    username: <%= ENV['GEOSERVER_DB_USERNAME'] || 'nds' %>
    password: <%= ENV['GEOSERVER_DB_PASSWORD'] || 'nds' %>
    host: <%= ENV['GEOSERVER_DB_HOST'] || 'localhost' %>
    port: <%= ENV['GEOSERVER_DB_PORT'] || '5000' %>

  pretend_admin: true
  cs:
    env: production
    search_endpoint: "https://search-nds-resources-22fi3bt2o7vt5wllh64qck52a4.us-east-1.cloudsearch.amazonaws.com"
    doc_endpoint: "https://doc-nds-resources-22fi3bt2o7vt5wllh64qck52a4.us-east-1.cloudsearch.amazonaws.com"
    #access_key: <%= ENV["CLOUDSEARCH_ACCESS_KEY"] %>
    #secret_key: <%= ENV["CLOUDSEARCH_SECRET_KEY"] %>

test:
  emails:
     broken_links:
        - noone@there.com
  postgres:
    adapter: <%= ENV['POSTGRES_DB_ADAPTER'] || 'postgres' %>
    database: <%= ENV['POSTGRES_DB_DATABASE'] || 'nds' %>
    username: <%= ENV['POSTGRES_DB_USERNAME'] || 'nds' %>
    password: <%= ENV['POSTGRES_DB_PASSWORD'] || 'nds' %>
    host: <%= ENV['POSTGRES_DB_HOST'] || 'localhost' %>
    port: <%= ENV['POSTGRES_DB_PORT'] || '5000' %>
  postgres_geoserver:
    adapter: <%= ENV['POSTGRES_DB_ADAPTER'] || 'postgres' %>
    database: <%= ENV['POSTGRES_DB_DATABASE'] || 'nds' %>
    username: <%= ENV['POSTGRES_DB_USERNAME'] || 'nds' %>
    password: <%= ENV['POSTGRES_DB_PASSWORD'] || 'nds' %>
    host: <%= ENV['POSTGRES_DB_HOST'] || 'localhost' %>
    port: <%= ENV['POSTGRES_DB_PORT'] || '5000' %>

  pretend_admin: false
  cs:
    env: test
    search_endpoint: "https://search-nds-resources-22fi3bt2o7vt5wllh64qck52a4.us-east-1.cloudsearch.amazonaws.com"
    doc_endpoint: "https://doc-nds-resources-22fi3bt2o7vt5wllh64qck52a4.us-east-1.cloudsearch.amazonaws.com"
    access_key: <%= ENV["CLOUDSEARCH_ACCESS_KEY"] %>
    secret_key: <%= ENV["CLOUDSEARCH_SECRET_KEY"] %>
